# TCL File Generated by Component Editor 21.1
# Mon Mar 21 16:40:40 MDT 2022
# DO NOT MODIFY


# 
# ad1939_audio_mini "AD1939 audio mini" v1.0
# Trevor Vannoy 2022.03.21.16:40:40
# AD1939 codec interface for converting between I2S and Avalon Stream
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ad1939_audio_mini
# 
set_module_property DESCRIPTION "AD1939 codec interface for converting between I2S and Avalon Stream"
set_module_property NAME ad1939_audio_mini
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Trevor Vannoy"
set_module_property DISPLAY_NAME "AD1939 audio mini"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ad1939_hps_audio_mini
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AD1939_hps_audio_mini.vhd VHDL PATH AD1939_hps_audio_mini.vhd TOP_LEVEL_FILE
add_fileset_file parallel2serial.vhdl VHDL PATH parallel2serial.vhdl
add_fileset_file serial2parallel.vhdl VHDL PATH serial2parallel.vhdl
add_fileset_file delay_signal.vhd VHDL PATH delay_signal.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point sys_clk
# 
add_interface sys_clk clock end
set_interface_property sys_clk clockRate 98304000
set_interface_property sys_clk ENABLED true
set_interface_property sys_clk EXPORT_OF ""
set_interface_property sys_clk PORT_NAME_MAP ""
set_interface_property sys_clk CMSIS_SVD_VARIABLES ""
set_interface_property sys_clk SVD_ADDRESS_GROUP ""

add_interface_port sys_clk sys_clk clk Input 1


# 
# connection point clk_abclk
# 
add_interface clk_abclk clock end
set_interface_property clk_abclk clockRate 12288000
set_interface_property clk_abclk ENABLED true
set_interface_property clk_abclk EXPORT_OF ""
set_interface_property clk_abclk PORT_NAME_MAP ""
set_interface_property clk_abclk CMSIS_SVD_VARIABLES ""
set_interface_property clk_abclk SVD_ADDRESS_GROUP ""

add_interface_port clk_abclk ad1939_adc_abclk clk Input 1


# 
# connection point clk_lrclk
# 
add_interface clk_lrclk clock end
set_interface_property clk_lrclk clockRate 192000
set_interface_property clk_lrclk ENABLED true
set_interface_property clk_lrclk EXPORT_OF ""
set_interface_property clk_lrclk PORT_NAME_MAP ""
set_interface_property clk_lrclk CMSIS_SVD_VARIABLES ""
set_interface_property clk_lrclk SVD_ADDRESS_GROUP ""

add_interface_port clk_lrclk ad1939_adc_alrclk clk Input 1


# 
# connection point sys_reset
# 
add_interface sys_reset reset end
set_interface_property sys_reset associatedClock sys_clk
set_interface_property sys_reset synchronousEdges DEASSERT
set_interface_property sys_reset ENABLED true
set_interface_property sys_reset EXPORT_OF ""
set_interface_property sys_reset PORT_NAME_MAP ""
set_interface_property sys_reset CMSIS_SVD_VARIABLES ""
set_interface_property sys_reset SVD_ADDRESS_GROUP ""

add_interface_port sys_reset sys_reset reset Input 1


# 
# connection point to_heaphone_out
# 
add_interface to_heaphone_out avalon_streaming end
set_interface_property to_heaphone_out associatedClock sys_clk
set_interface_property to_heaphone_out associatedReset sys_reset
set_interface_property to_heaphone_out dataBitsPerSymbol 24
set_interface_property to_heaphone_out errorDescriptor ""
set_interface_property to_heaphone_out firstSymbolInHighOrderBits true
set_interface_property to_heaphone_out maxChannel 1
set_interface_property to_heaphone_out readyLatency 0
set_interface_property to_heaphone_out ENABLED true
set_interface_property to_heaphone_out EXPORT_OF ""
set_interface_property to_heaphone_out PORT_NAME_MAP ""
set_interface_property to_heaphone_out CMSIS_SVD_VARIABLES ""
set_interface_property to_heaphone_out SVD_ADDRESS_GROUP ""

add_interface_port to_heaphone_out ad1939_dac_data data Input 24
add_interface_port to_heaphone_out ad1939_dac_channel channel Input 1
add_interface_port to_heaphone_out ad1939_dac_valid valid Input 1


# 
# connection point from_line_in
# 
add_interface from_line_in avalon_streaming start
set_interface_property from_line_in associatedClock sys_clk
set_interface_property from_line_in associatedReset sys_reset
set_interface_property from_line_in dataBitsPerSymbol 24
set_interface_property from_line_in errorDescriptor ""
set_interface_property from_line_in firstSymbolInHighOrderBits true
set_interface_property from_line_in maxChannel 1
set_interface_property from_line_in readyLatency 0
set_interface_property from_line_in ENABLED true
set_interface_property from_line_in EXPORT_OF ""
set_interface_property from_line_in PORT_NAME_MAP ""
set_interface_property from_line_in CMSIS_SVD_VARIABLES ""
set_interface_property from_line_in SVD_ADDRESS_GROUP ""

add_interface_port from_line_in ad1939_adc_data data Output 24
add_interface_port from_line_in ad1939_adc_channel channel Output 1
add_interface_port from_line_in ad1939_adc_valid valid Output 1


# 
# connection point connect_to_ad1939_1
# 
add_interface connect_to_ad1939_1 conduit end
set_interface_property connect_to_ad1939_1 associatedClock clk_abclk
set_interface_property connect_to_ad1939_1 associatedReset sys_reset
set_interface_property connect_to_ad1939_1 ENABLED true
set_interface_property connect_to_ad1939_1 EXPORT_OF ""
set_interface_property connect_to_ad1939_1 PORT_NAME_MAP ""
set_interface_property connect_to_ad1939_1 CMSIS_SVD_VARIABLES ""
set_interface_property connect_to_ad1939_1 SVD_ADDRESS_GROUP ""

add_interface_port connect_to_ad1939_1 ad1939_adc_asdata2 asdata2 Input 1
add_interface_port connect_to_ad1939_1 ad1939_dac_dsdata1 dsdata1 Output 1
add_interface_port connect_to_ad1939_1 ad1939_dac_dbclk dbclk Output 1
add_interface_port connect_to_ad1939_1 ad1939_dac_dlrclk dlrclk Output 1

